import { JArray } from "@zwa73/utils";
import { saveStaticData } from "./StaticData";

export const ControlSpellFlags = ["SILENT", "NO_HANDS", "NO_LEGS", "NO_FAIL"];
export const BaseSpell:JArray = [
	{
		type: "SPELL",
		id: "CustomNPC_SPELL_SummonTarget",
		name: "召唤标靶",
		description: "召唤标靶怪物",
		flags: ["HOSTILE_SUMMON",...ControlSpellFlags],
		valid_targets: ["ground"],
		min_damage: 1,
		max_damage: 1,
		min_aoe: 1,
		max_aoe: 1,
		effect: "summon",
		effect_str: "mon_chicken",
		min_duration: 1,
		max_duration: 1,
		shape: "blast",
	},
	{
		type: "SPELL",
		id: "CustomNPC_SPELL_InitCurrHP",
		name: "初始化当前生命值",
		description: "初始化当前生命值变量",
		flags: ControlSpellFlags,
		valid_targets: ["hostile"],
		min_aoe: 20,
		max_aoe: 20,
		effect: "effect_on_condition",
		effect_str: "CustomNPC_EOC_InitCurrHP",
		shape: "blast",
	},
	{
		type: "SPELL",
		id: "CustomNPC_SPELL_CheckCurrHP",
		name: "检测当前生命值",
		description: "检测当前生命值是否有变动",
		flags: ControlSpellFlags,
		valid_targets: ["hostile"],
		min_aoe: 20,
		max_aoe: 20,
		effect: "effect_on_condition",
		effect_str: "CustomNPC_EOC_CheckCurrHP",
		shape: "blast",
	},
	{
		id: "CustomNPC_SPELL_TestConeSpell_DMG",
		type: "SPELL",
		name: "测试用锥形法术 伤害部分",
		description: "测试用锥形法术 伤害部分",
		effect: "attack",
		shape: "cone",
		valid_targets: ["hostile", "ground"],
		min_damage: 100,
		max_damage: 100,
		min_aoe: 90,
		min_range: 20,
		base_casting_time: 100,
		damage_type: "heat",
	},
	{
		id: "CustomNPC_SPELL_TestConeSpell",
		type: "SPELL",
		name: "测试用锥形法术",
		description: "测试用锥形法术",
		effect: "attack",
		shape: "cone",
		valid_targets: ["hostile"],
		flags: ["WONDER", "RANDOM_TARGET",...ControlSpellFlags],
		min_damage: 1,
		max_damage: 1,
		min_aoe: 90,
		min_range: 20,
		base_casting_time: 100,
		extra_effects: [{ id: "CustomNPC_SPELL_TestConeSpell_DMG" }],
		targeted_monster_ids: ["mon_chicken"],
	}
];


saveStaticData('BaseSpell',BaseSpell);